version: '3'
services:
  gulp:
    container_name: i2btech-storybook
    hostname: i2btech-storybook
    image: node:14.4
    working_dir: /app
    volumes:
      - ../:/app
    command: [ "/bin/bash", "-c", "docker/bin/start.sh" ]
    ports:
      - 65200:65200